services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env

  frontend-admin:
    build:
      context: ./frontend-admin
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend-admin:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001

  frontend-b2c:
    build:
      context: ./frontend-b2c
      dockerfile: Dockerfile
    ports:
      - '3002:3000'
    volumes:
      - ./frontend-b2c:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
